Dylan impl
webbdylan/Learning-CS-Fundamentals pull request #12
Opened 2017-02-18 14:16 UTC by webbdylan

stack implementation working

2017-02-18 15:37 UTC, iAmWillShepherd requested changes

2017-02-18 15:37 UTC, iAmWillShepherd commented on data_structures/src/Stack/Stack.cs
> +        private T[] _stack { get; set; }
Call this `items` to make it clear what it is. Your internal representation of the data is not equal to the behavior of your data structure - in this case, a stack.

2017-02-18 15:37 UTC, iAmWillShepherd commented on data_structures/src/Stack/Stack.cs
> +            return this.Size() > 0 ? false : true;
No need for the `this` keyword, it is noisy and redundant in a language like c#. You also don't need this ternary expression; `return this.Size() > 0` is sufficient.

2017-02-18 15:37 UTC, iAmWillShepherd commented on data_structures/src/Stack/Stack.cs
> +                throw new Exception("Stack is empty- Cannot peek.");
Nitpick: change `"Stack is empty- Cannot peek."` to `"Stack is empty - Cannot peek."`

2017-02-18 15:37 UTC, iAmWillShepherd commented on data_structures/src/Stack/Stack.cs
> +                var returnItem =  _stack[_lastIndex -1];
You have a method, `Peek` that does most of this for you, why not use it??? 😉

2017-02-18 15:37 UTC, iAmWillShepherd commented on data_structures/src/Stack/Stack.cs
> +                _lastIndex--;
Don't forget to also erase the data in `_lastIndex` before decrementing it. Something like `_stack[lastIndex--] = default(T)` should do (note, I have not tried this).

2017-02-18 15:37 UTC, iAmWillShepherd commented on data_structures/src/Stack/Stack.cs
> +                _lastIndex++;
You can shorten this line by doing `_stack[_lastIndex++] = item;` Also, if you only have one statement following an if else block, no need for braces, they are noisy.

2017-02-18 15:37 UTC, iAmWillShepherd commented on data_structures/src/Stack/Stack.cs
> +            return _lastIndex;
It seems you are using `_lastIndex` as a way to know where the top of the stack is, why not name it accordingly?

2017-02-18 15:37 UTC, iAmWillShepherd commented on data_structures/test/Stack.Tests/Tests.cs
> -            for (var i = 0; i < 10; i++)
Nice catch! This is what happens when you code at 🌙 !

2017-02-18 15:39 UTC, iAmWillShepherd commented
Overall, this is good stuff 👍 . Did you read the [notes](http://algs4.cs.princeton.edu/13stacks/) on the uses of stacks? If not, I'd recommend it. We will be continuing with the stack implementation to make it more useful! I promise it will get more exciting!!!

2017-02-19 04:23 UTC, webbdylan commented
I skimmed over the article, but will do it again. I'll also get to your
corrections tomorrow sometime.

I did notice your suggestion on the 'this.'... i do agree, must've had
typescript on the brain.

Gotta run, catching up on some lost work hours at the moment...

-Dylan

On Sat, Feb 18, 2017 at 9:39 AM, William Shepherd <notifications@github.com>
wrote:

> Overall, this is good stuff 👍 . Did you read the notes
> <http://algs4.cs.princeton.edu/13stacks/> on the uses of stacks? If not,
> I'd recommend it. We will be continuing with the stack implementation to
> make it more useful! I promise it will get more exciting!!!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/webbdylan/Learning-CS-Fundamentals/pull/12#issuecomment-280853102>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AILFbQMMXoklKc-rRWTtxskXUPqN3Lklks5rdxCbgaJpZM4MFIhR>
> .
>

2017-02-19 05:04 UTC, iAmWillShepherd commented
Yea I figured the `this` thing was from TS, I deal with it daily. I'll be on a plane to LA tomorrow morning so I'll review it once I land. Just a heads up, the next task will be to implement a dynamically sized stack! Something to think about.

2017-02-19 20:07 UTC, webbdylan commented on data_structures/src/Stack/Stack.cs
> +                throw new Exception("Stack is empty- Cannot peek.");
ive been using dashes wrong my entire life... lol

2017-02-20 01:53 UTC, iAmWillShepherd approved these changes

2017-02-20 01:53 UTC, iAmWillShepherd commented on data_structures/src/Stack/Stack.cs
> +                throw new Exception("Stack is empty - Cannot peek.");
Just wanted to point out that it's better style to check for error conditions and return as soon as possible. So swapping the conditional to:

```cs
public T Peek()
{
	if(IsEmpty())
	    throw new Exception("Stack is empty - Cannot peek.");

	return _items[_topOfStack -1];
}
```
Basically the else should only be used for things that matter.

2017-02-20 01:53 UTC, merged